import Head from 'next/head'
import Chat from '@/components/Chat';
import { useIdentity } from '@/providers/Identity';
import { useRouter } from 'next/router';
import { useMesseger } from '@/providers/Messenger';
import { Identity } from 'orbit-db-identity-provider';
import makeBlockie from 'ethereum-blockies-base64';

export default function Talk() {

  const router = useRouter();
  const { to } = router.query;

  const { identity } = useIdentity();
  const { messages, send, isLoading } = useMesseger(identity as Identity, to as string);

  return (
    <div className='bg-gray-50 w-full h-screen flex justify-center'>
      <Head>
        <title>TalkTime Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full max-w-3xl bg-white sm:border-x border-gray-100">
        <Chat
          contact={{
            label: to as string,
            picture: makeBlockie(to as string)
          }}
          messages={messages}
          initialMsg=''
          onSend={(msg) => send(msg)}
          isLoading={isLoading}
        />
      </main>
    </div>
  )
}